#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bonso"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 8


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/community"
    weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Hi, my name is Adam Howard. I’m a writer and photographer based in Portland. I like being at the center of events, being free and enjoying every moment."

  #-------------------------------
  # Author Settings
  [params.author]
    avatar = "https://via.placeholder.com/200x200"
    name = "Juan Manuel Ferrera"
    job = "Passionate Writer & Organizer"


  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-dribbble"
    name = "Dribbble"
    link = "https://dribbble.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com/"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Featured Slider
  [params.slider]
    slider__image = "true" # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  [params.mailchimp]
    mailchimp = "true" # If you do not want to use Subscribe form, leave the mailchimp field empty.
    mailchimp__title = "Get Interesting News"
    mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your email for contant form

    # NOTE
    # Aditu comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = "anvodstudio-demo" # add your shortname for Disqus Comment. For example anvodstudio-demo


[related]
  includeNewer = true
  threshold = 85
  toLower = false

  [[related.indices]]
  name = "tags"
  weight = 80

  [[related.indices]]
  name = "keywords"
  weight = 40

  [[related.indices]]
  name = "date"
  weight = 10


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
